<a href="https://colab.research.google.com/github/KevinYuen/PythonDataScienceLearning/blob/main/DataScienceLearningNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic Numpy Arrays

![avatar](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

In [ ]:
import sys
import numpy as np

a = np.array([1,2,3,4])
print(a.dtype)

a = np.array([1,2,3,4], dtype=np.int8)
print(a.dtype)

A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
], dtype=np.int8)

print(A)
print(A[:, :2])


int64
int8
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]


# Instruction of Panda


![avatar](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

In [14]:
import pandas as pd
import numpy as np

g7_pop = pd.Series([35.467, 63.951, 80.940, 60.655, 127.061, 64.511, 318.523])
g7_pop.name = "G7 population in millions"
g7_pop

0     35.467
1     63.951
2     80.940
3     60.655
4    127.061
5     64.511
6    318.523
Name: G7 population in millions, dtype: float64

In [10]:
g7_pop.dtype

dtype('float64')

In [11]:
g7_pop.name

'G7 population in millions'

In [12]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.655, 127.061,  64.511, 318.523])

In [13]:
type(g7_pop.values)

numpy.ndarray

In [15]:
g7_pop[1]

63.951

In [16]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [17]:
g7_pop.index = [
                "Canada",
                "France",
                "Germany",
                "Italy",
                "Japan",
                "United Kindom",
                "United States"
]
g7_pop.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kindom',
       'United States'],
      dtype='object')

In [18]:
g7_pop

Canada            35.467
France            63.951
Germany           80.940
Italy             60.655
Japan            127.061
United Kindom     64.511
United States    318.523
Name: G7 population in millions, dtype: float64