<a href="https://colab.research.google.com/github/KevinYuen/PythonDataScienceLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic Numpy Arrays

In [1]:
import sys
import numpy as np

a = np.array([1,2,3,4])
print(a.dtype)

a = np.array([1,2,3,4], dtype=np.int8)
print(a.dtype)

A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
], dtype=np.int8)

print(A)
print(A[:, :2])


int64
int8
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]


# Instruction of Panda


In [9]:
import pandas as pd
import numpy as np

g7_pop = pd.Series([35.467, 63.951, 80.940, 60.655, 127.061, 64.511, 318.523])
g7_pop.name = "G7 population in millions"
print(g7_pop)
print(g7_pop.dtype)
print(g7_pop.name)
print(g7_pop.values)
print(type(g7_pop.values))

0     35.467
1     63.951
2     80.940
3     60.655
4    127.061
5     64.511
6    318.523
Name: G7 population in millions, dtype: float64
float64
G7 population in millions
[ 35.467  63.951  80.94   60.655 127.061  64.511 318.523]
<class 'numpy.ndarray'>
