<a href="https://colab.research.google.com/github/KevinYuen/PythonDataScienceLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic Numpy Arrays

In [12]:
import sys
import numpy as np

a = np.array([1,2,3,4])
print(a.dtype)

a = np.array([1,2,3,4], dtype=np.int8)
print(a.dtype)

A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
], dtype=np.int8)

print(A)
print(A[:, :2])


int64
int8
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
